package com.plkrhone.sisrh.model;

public enum Nacionalidade {
	ANTIGUA_E_BARBUDA("Antígua e Barbuda"),
	ARGENTINA("Argentina"),
	BAHAMAS("Bahamas"),
	BARBADOS("Barbados"),
	BELIZE("Belize"),
	BOLIVIA("Bolívia"),
	BRASIL("Brasil"),
	CHILE("Chile"),
	COLOMBIA("Colômbia"),
	COSTA_RICA("Costa Rica"),
	CUBA("Cuba"),
	DOMINICA("Dominica"),
	EQUADOR("Equador"),
	EL_SALVADOR("El Salvador"),
	GRANADA("Granada"),
	GUATEMALA("Guatemala"),
	GUIANA("Guiana"),
	GUIANA_FRANCESA("Guiana Francesa"),
	HAITI("Haiti"),
	HONDURAS("Honduras"),
	JAMAICA("Jamaica"),
	MEXICO("México"),
	NICARAGUA("Nicarágua"),
	PANAMA("Panamá"),
	PARAGUAI("Paraguai"),
	PERU("Peru"),
	PORTO_RICO("Porto Rico"),
	REPUBLICA_DOMINICANA("República Dominicana"),
	SAO_CRISTOVAO_E_NEVIS("São Cristóvão e Nevis"),
	SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
	SANTA_LUCIA("Santa Lúcia"),
	SURINAME("Suriname"),
	TRINIDAD_E_TOBAGO("Trinidad e Tobago"),
	URUGUAI("Uruguai"),
	VENEZUELA("Venezuela"),
	ALEMANHA("Alemanha"),
	AUSTRIA("Austria"),
	BELGICA("Bélgica"),
	CROACIA("Croácia"),
	DINAMARCA("Dinamarca"),
	ESLOVAQUIA("Eslováquia"),
	ESLOVENIA("Eslovênia"),
	ESPANHA("Espanha"),
	FRANCA("França"),
	GRECIA("Grécia"),
	HUNGRIA("Hungria"),
	IRLANDA("Irlanda"),
	ITALIA("Itália"),
	NORUEGA("Noruega"),
	PAISES_BAIXOS("Países Baixos"),
	POLONIA("Polônia"),
	PORTUGAL("Portugal"),
	REINO_UNIDO("Reino Unido"),
	INGLATERRA("Inglaterra"),
	PAIS_DE_GALES("País de Gales"),
	ESCOCIA("Escócia"),
	ROMENIA("Romênia"),
	RUSSIA("Rússia"),
	SERVIO("Sérvio"),
	SUECIA("Suécia"),
	SUICA("Suíça"),
	TURQUIA("Turquia"),
	UCRANIA("Ucrânia"),
	ESTADOS_UNIDOS("Estados Unidos"),
	CANADA("Canadá"),
	ANGOLA("Angola"),
	MOCAMBIQUE("Moçambique"),
	AFRICA_DO_SUL("Africa do Sul"),
	ZIMBABUE("Zimbabue"),
	ARGELIA("Argélia"),
	COMORES("Comores"),
	EGITO("Egito"),
	LIBIA("Líbia"),
	MARROCOS("Marrocos"),
	GANA("Gana"),
	QUENIA("Quênia"),
	RUANDA("Ruanda"),
	UGANDA("Uganda"),
	BOTSUANA("Botsuana"),
	COSTA_DO_MARFIM("Costa do Marfim"),
	CAMAROES("Camarões"),
	NIGERIA("Nigéria"),
	SOMALIA("Somália"),
	AUSTRALIA("Austrália"),
	NOVA_ZELANDIA("Nova Zelândia"),
	AFEGANISTAO("Afeganistão"),
	ARABIA_SAUDITA("Arábia Saudita"),
	ARMENIA("Armênia"),
	ARMENO("Armeno"),
	CHINA("China"),
	COREIA_DO_NORTE("Coréia do Norte"),
	COREIA_DO_SUL("Coréia do Sul"),
	INDIA("India"),
	INDONESIA("Indonésia"),
	IRAQUE("Iraque"),
	IRA("Irã"),
	ISRAEL("Israel"),
	JAPAO("Japão"),
	MALASIA("Malásia"),
	NEPAL("Nepal"),
	OMA("Omã"),
	PAQUISTAO("Paquistão"),
	PALESTINA("Palestina"),
	QATAR("Qatar"),
	SIRIA("Síria"),
	SRI_LANKA("Sri Lanka"),
	TAILANDIA("Tailândia"),
	TIMOR("Timor"),
	EMIRADOS_ARABES_UNIDOS("Emirados Arabes Unidos"),
	VIETNA("Vietnã"),
	IEMEN("Iêmen");
	private String descricao;
	Nacionalidade(String descricao){
		this.descricao=descricao;
	}
	 public String getDescricao() {
		return descricao;
	}
}
